# Generated by Django 2.2.4 on 2021-01-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_billingaddress_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
